name = input("Enter Name: ")
address = input("Enter Address: ")
email = input("Enter Email-ID: ")
phone = int(input("Enter Phone Number: "))
print(f"Name:{name}")
print(f"Address:{address}")
print(f"Email-ID:{email}")
print(f"Phone Number:{phone}")
